[project]
name = "path-finder"
version = "0.1.0"
description = "Segmentation model for detecting hiking paths along the coast in satellite images."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "albumentations>=2.0.8",
    "fiona>=1.10.1",
    "folium>=0.20.0",
    "geopandas>=1.1.1",
    "keras>=3.11.3",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "owslib>=0.34.1",
    "pyproj>=3.7.2",
    "rasterio>=1.4.3",
    "rioxarray>=0.19.0",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.2",
    "segmentation-models-pytorch>=0.5.0",
    "shapely>=2.1.2",
    "tensorflow>=2.20.0",
    "torch>=2.9.0",
    "torchmetrics>=1.8.2",
]
