data:
  raw_geotiffs_dir: data/raw/geotiffs
  raw_labels_dir: data/labels
  processed_dir: data/processed
  tiles_dir: data/interim/tiles
  patch_size: 512 # size of patches to extract from geotiffs for processing

tiles:
  tile_size: 4096 # original image is split into tiles of this size
  target_size: 256 # 4096 tiles are downsampled to this size for model input
  path_pixel_dilation: 40 # make the path wider -> counters class imbalance, more realistic
  augmentations:
    - horizontal_flip
    - vertical_flip
    - rotation_90